/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package azuelorhoderick.Screens;

import javax.swing.JOptionPane;

import azuelorhoderick.DBConnection;
import java.sql.*;
import javax.swing.ButtonGroup;

public class AdjustStockScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdjustStockScreen.class.getName());
    private Integer selectedProductId = null;
    private final ButtonGroup adjustGroup = new ButtonGroup();
    private final Dashboard dashboard;
    
   


  
    public AdjustStockScreen() {
    this(null);
}

public AdjustStockScreen(Dashboard dashboard) {
    initComponents();
    if (dashboard != null) {
    dashboard.loadInventoryToTable();
    dashboard.loadProductsToTable();
}

    this.dashboard = dashboard;
    setupRadioButtons();
    loadProductsToCombo();
    setupProductComboListener();
    setupRadioButtons();

}

   
    
    private void setupRadioButtons() {
    adjustGroup.add(add_radiobutton);
    adjustGroup.add(remove_radiobutton);
    adjustGroup.add(setExactStock_radiobutton);

    // optional: default selection
    add_radiobutton.setSelected(true);
}
    
    private void loadProductsToCombo() {
    product_txt.removeAllItems();
    product_txt.addItem("-- Select Product --");

    String sql = "SELECT product_id, product_name FROM products ORDER BY product_name ASC";

    try (Connection con = DBConnection.getConnection();
         PreparedStatement pst = con.prepareStatement(sql);
         ResultSet rs = pst.executeQuery()) {

        while (rs.next()) {
            int id = rs.getInt("product_id");
            String name = rs.getString("product_name");
            product_txt.addItem(id + " - " + name);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading products: " + e.getMessage());
        e.printStackTrace();
    }
}

    
    private void setupProductComboListener() {
    product_txt.addActionListener(e -> {
        if (product_txt.getSelectedIndex() <= 0) {
            selectedProductId = null;
            clearProductDetails();
            return;
        }

        String selected = String.valueOf(product_txt.getSelectedItem());
        int dashIndex = selected.indexOf(" - ");
        if (dashIndex <= 0) return;

        selectedProductId = Integer.parseInt(selected.substring(0, dashIndex).trim());
        loadSelectedProductDetails(selectedProductId);
    });
}

       private void clearProductDetails() {
    barcode1_txt.setText("");
    barcode_txt.setText("");
    currentStock_lbl.setText("");
}
       
       
       private void loadSelectedProductDetails(int productId) {
    String sql =
        "SELECT p.barcode, COALESCE(i.current_stock,0) AS current_stock " +
        "FROM products p " +
        "LEFT JOIN inventory i ON i.product_id = p.product_id " +
        "WHERE p.product_id = ?";

    try (Connection con = DBConnection.getConnection();
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setInt(1, productId);
        try (ResultSet rs = pst.executeQuery()) {
            if (rs.next()) {
                String barcode = rs.getString("barcode");
                int currentStock = rs.getInt("current_stock");

                barcode1_txt.setText(barcode);
                barcode_txt.setText(barcode);
                currentStock_lbl.setText(String.valueOf(currentStock));
            } else {
                clearProductDetails();
            }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading product details: " + e.getMessage());
        e.printStackTrace();
    }
}

       
       






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        barcode_txt = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        barcode1_txt = new javax.swing.JLabel();
        product_txt = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        currentStock_lbl = new javax.swing.JLabel();
        setExactStock_radiobutton = new javax.swing.JRadioButton();
        add_radiobutton = new javax.swing.JRadioButton();
        remove_radiobutton = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        quantity_txt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reason_txt = new javax.swing.JTextArea();
        cancel_txt = new javax.swing.JButton();
        saveAdjustment_txt = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(686, 530));
        setMinimumSize(new java.awt.Dimension(686, 530));
        setPreferredSize(new java.awt.Dimension(686, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 247, 251));
        jPanel1.setMaximumSize(new java.awt.Dimension(686, 530));
        jPanel1.setMinimumSize(new java.awt.Dimension(686, 530));
        jPanel1.setPreferredSize(new java.awt.Dimension(686, 530));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/azuelorhoderick/azueloIcons/barcode.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        barcode_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        barcode_txt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(barcode_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 110, 30));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 750, 1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Barcode:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 60, 30));

        barcode1_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        barcode1_txt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(barcode1_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 110, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 630, 70));

        product_txt.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(product_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 570, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Reason");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 70, 20));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 680, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Adjust Stock");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 8, 160, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Product:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, 30));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 630, 1));

        currentStock_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        currentStock_lbl.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(currentStock_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 100, 30));

        setExactStock_radiobutton.setBackground(new java.awt.Color(255, 255, 255));
        setExactStock_radiobutton.setText("Set Exact Stock");
        setExactStock_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setExactStock_radiobuttonActionPerformed(evt);
            }
        });
        jPanel1.add(setExactStock_radiobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        add_radiobutton.setBackground(new java.awt.Color(255, 255, 255));
        add_radiobutton.setForeground(new java.awt.Color(0, 0, 0));
        add_radiobutton.setText("Add");
        add_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_radiobuttonActionPerformed(evt);
            }
        });
        jPanel1.add(add_radiobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 60, -1));

        remove_radiobutton.setBackground(new java.awt.Color(255, 255, 255));
        remove_radiobutton.setText("Remove");
        remove_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_radiobuttonActionPerformed(evt);
            }
        });
        jPanel1.add(remove_radiobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Adjustment Type:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 140, 40));

        quantity_txt.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(quantity_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 160, 30));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 630, 1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Quantity:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 70, 50));

        reason_txt.setBackground(new java.awt.Color(255, 255, 255));
        reason_txt.setColumns(20);
        reason_txt.setRows(5);
        jScrollPane1.setViewportView(reason_txt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 630, -1));

        cancel_txt.setBackground(new java.awt.Color(204, 204, 204));
        cancel_txt.setForeground(new java.awt.Color(0, 0, 0));
        cancel_txt.setText("Cancel");
        cancel_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_txtActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 120, 40));

        saveAdjustment_txt.setBackground(new java.awt.Color(153, 0, 0));
        saveAdjustment_txt.setText("Save Adjustment");
        saveAdjustment_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAdjustment_txtActionPerformed(evt);
            }
        });
        jPanel1.add(saveAdjustment_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 120, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Current Stock:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 686, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_radiobuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_radiobuttonActionPerformed

    private void remove_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_radiobuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remove_radiobuttonActionPerformed

    private void setExactStock_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setExactStock_radiobuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setExactStock_radiobuttonActionPerformed

    private void cancel_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_txtActionPerformed
        // TODO add your handling code here:
         int choice = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to go back to Dashboard?",
        "Confirm Exit",
        JOptionPane.YES_NO_OPTION
    );

    if (choice == JOptionPane.YES_OPTION) {
        this.dispose();
    }
        
    }//GEN-LAST:event_cancel_txtActionPerformed

    private void saveAdjustment_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAdjustment_txtActionPerformed
        // TODO add your handling code here:
        if (selectedProductId == null) {
        JOptionPane.showMessageDialog(this, "Please select a product.");
        return;
    }

    // Validate qty
    String qtyText = quantity_txt.getText().trim();
    if (qtyText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Quantity is required.");
        quantity_txt.requestFocus();
        return;
    }

    int qty;
    try {
        qty = Integer.parseInt(qtyText);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Quantity must be a valid number.");
        quantity_txt.requestFocus();
        return;
    }

    if (qty < 0) {
        JOptionPane.showMessageDialog(this, "Quantity cannot be negative.");
        quantity_txt.requestFocus();
        return;
    }

    String reason = reason_txt.getText().trim();
    if (reason.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Reason is required.");
        reason_txt.requestFocus();
        return;
    }

    boolean isAdd = add_radiobutton.isSelected();
    boolean isRemove = remove_radiobutton.isSelected();
    boolean isSetExact = setExactStock_radiobutton.isSelected();

    if (!isAdd && !isRemove && !isSetExact) {
        JOptionPane.showMessageDialog(this, "Please select an adjustment type.");
        return;
    }

    // Current stock from label
    int currentStock = 0;
    try { currentStock = Integer.parseInt(currentStock_lbl.getText().trim()); }
    catch (Exception ignore) {}

    // Compute new stock + movement type
    int newStock;
    String movementType;

    if (isAdd) {
        if (qty == 0) { JOptionPane.showMessageDialog(this, "Add quantity must be > 0."); return; }
        newStock = currentStock + qty;
        movementType = "IN";
    } else if (isRemove) {
        if (qty == 0) { JOptionPane.showMessageDialog(this, "Remove quantity must be > 0."); return; }
        if (qty > currentStock) {
            JOptionPane.showMessageDialog(this, "Cannot remove more than current stock.");
            return;
        }
        newStock = currentStock - qty;
        movementType = "OUT";
    } else { // set exact
        newStock = qty;
        movementType = "SET";
    }

    String ensureInventoryRow =
        "INSERT INTO inventory (product_id, quantity_in, quantity_out, current_stock, last_updated) " +
        "VALUES (?, 0, 0, 0, NOW()) " +
        "ON DUPLICATE KEY UPDATE last_updated = NOW()";

    String addSql =
        "UPDATE inventory " +
        "SET quantity_in = quantity_in + ?, current_stock = current_stock + ?, last_updated = NOW() " +
        "WHERE product_id = ?";

    String removeSql =
        "UPDATE inventory " +
        "SET quantity_out = quantity_out + ?, current_stock = current_stock - ?, last_updated = NOW() " +
        "WHERE product_id = ?";

    String setExactSql =
        "UPDATE inventory SET current_stock = ?, last_updated = NOW() WHERE product_id = ?";

    String movSql =
        "INSERT INTO inventory_movements (product_id, movement_type, quantity, movement_date, notes) " +
        "VALUES (?, ?, ?, NOW(), ?)";

    String statusSql =
        "UPDATE products p " +
        "JOIN inventory i ON i.product_id = p.product_id " +
        "SET p.status = CASE WHEN i.current_stock > 0 THEN 'Available' ELSE 'Out of Stock' END " +
        "WHERE p.product_id = ?";

    try (Connection con = DBConnection.getConnection()) {
        con.setAutoCommit(false);

        try {
            // 1) ensure inventory row exists
            try (PreparedStatement p = con.prepareStatement(ensureInventoryRow)) {
                p.setInt(1, selectedProductId);
                p.executeUpdate();
            }

            // 2) update inventory
            if (isAdd) {
                try (PreparedStatement pst = con.prepareStatement(addSql)) {
                    pst.setInt(1, qty);
                    pst.setInt(2, qty);
                    pst.setInt(3, selectedProductId);
                    pst.executeUpdate();
                }
            } else if (isRemove) {
                try (PreparedStatement pst = con.prepareStatement(removeSql)) {
                    pst.setInt(1, qty);
                    pst.setInt(2, qty);
                    pst.setInt(3, selectedProductId);
                    pst.executeUpdate();
                }
            } else {
                try (PreparedStatement pst = con.prepareStatement(setExactSql)) {
                    pst.setInt(1, newStock);
                    pst.setInt(2, selectedProductId);
                    pst.executeUpdate();
                }
            }

            // 3) movement history
            try (PreparedStatement mv = con.prepareStatement(movSql)) {
                mv.setInt(1, selectedProductId);
                mv.setString(2, movementType);
                mv.setInt(3, qty);         // keep qty positive; movementType indicates direction
                mv.setString(4, reason);
                mv.executeUpdate();
            }

            // 4) update product status
            try (PreparedStatement st = con.prepareStatement(statusSql)) {
                st.setInt(1, selectedProductId);
                st.executeUpdate();
            }

            con.commit();

        } catch (Exception ex) {
            con.rollback();
            throw ex;
        }

        JOptionPane.showMessageDialog(this,
            "✅ Stock adjusted successfully!\n" +
            "Previous Stock: " + currentStock + "\n" +
            "New Stock: " + newStock + "\n" +
            "Reason: " + reason
        );

        // refresh labels
        loadSelectedProductDetails(selectedProductId);

        // refresh dashboard tables
        if (dashboard != null) {
            dashboard.loadInventoryToTable();
            dashboard.loadProductsToTable();
        }

        // clear inputs
        quantity_txt.setText("");
        reason_txt.setText("");

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
    }
    }//GEN-LAST:event_saveAdjustment_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdjustStockScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton add_radiobutton;
    private javax.swing.JLabel barcode1_txt;
    private javax.swing.JLabel barcode_txt;
    private javax.swing.JButton cancel_txt;
    private javax.swing.JLabel currentStock_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> product_txt;
    private javax.swing.JTextField quantity_txt;
    private javax.swing.JTextArea reason_txt;
    private javax.swing.JRadioButton remove_radiobutton;
    private javax.swing.JButton saveAdjustment_txt;
    private javax.swing.JRadioButton setExactStock_radiobutton;
    // End of variables declaration//GEN-END:variables
}
