/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package azuelorhoderick.Screens;

import javax.swing.JOptionPane;

/**
 *
 * @author Azuelo-Rh
 */
public class ProductScreen extends javax.swing.JFrame {

    /**
     * Creates new form ProductScreen
     */
    public ProductScreen() {
        initComponents();
        
        product_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int selectedRow = product_tbl.getSelectedRow();
            if (selectedRow >= 0) {
                // Get values from table
                productID_txt.setText(product_tbl.getValueAt(selectedRow, 0).toString());
                productName_txt.setText(product_tbl.getValueAt(selectedRow, 1).toString());
                category_cmb.setSelectedItem(product_tbl.getValueAt(selectedRow, 2).toString());
                description_txt.setText(product_tbl.getValueAt(selectedRow, 3).toString());
                costPrice_txt.setText(product_tbl.getValueAt(selectedRow, 4).toString());
                sellingPrice_txt.setText(product_tbl.getValueAt(selectedRow, 5).toString());
                quantity_txt.setText(product_tbl.getValueAt(selectedRow, 6).toString());
                reorder_txt.setText(product_tbl.getValueAt(selectedRow, 7).toString());
                supplier_txt.setText(product_tbl.getValueAt(selectedRow, 8).toString());
                unitMeasure_cmb.setSelectedItem(product_tbl.getValueAt(selectedRow, 9).toString());
                productStat_cmb.setSelectedItem(product_tbl.getValueAt(selectedRow, 10).toString());
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        exit_btn = new java.awt.Button();
        add_btn = new java.awt.Button();
        clear_btn = new java.awt.Button();
        update_btn = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        description_txt = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        productName_txt = new javax.swing.JTextField();
        reorder_txt = new javax.swing.JTextField();
        costPrice_txt = new javax.swing.JTextField();
        sellingPrice_txt = new javax.swing.JTextField();
        quantity_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        productStat_cmb = new javax.swing.JComboBox<>();
        productID_txt = new javax.swing.JTextField();
        supplier_txt = new javax.swing.JTextField();
        category_cmb = new javax.swing.JComboBox<>();
        unitMeasure_cmb = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        product_tbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product Screen");
        setMaximumSize(new java.awt.Dimension(650, 780));
        setMinimumSize(new java.awt.Dimension(650, 780));
        setPreferredSize(new java.awt.Dimension(650, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(650, 780));
        jPanel1.setMinimumSize(new java.awt.Dimension(650, 780));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("DESCRIPTION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Reorder Level");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 90, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Product Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 30));

        exit_btn.setLabel("EXIT");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 100, -1));

        add_btn.setLabel("ADD");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        jPanel1.add(add_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 100, -1));

        clear_btn.setLabel("CLEAR");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        jPanel1.add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 100, -1));

        update_btn.setLabel("UPDATE");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel1.add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, 100, -1));

        description_txt.setBackground(new java.awt.Color(255, 255, 255));
        description_txt.setColumns(20);
        description_txt.setRows(5);
        jScrollPane1.setViewportView(description_txt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 320, 100));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Product Category");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ADDITIONAL DETAILS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 230, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Product Status");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Selling Price");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 80, 50));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Quantity In Stock");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        productName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productName_txtActionPerformed(evt);
            }
        });
        jPanel1.add(productName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 200, 30));

        reorder_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reorder_txtActionPerformed(evt);
            }
        });
        jPanel1.add(reorder_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 120, 30));

        costPrice_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costPrice_txtActionPerformed(evt);
            }
        });
        jPanel1.add(costPrice_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 120, 30));

        sellingPrice_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellingPrice_txtActionPerformed(evt);
            }
        });
        jPanel1.add(sellingPrice_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 120, 30));

        quantity_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantity_txtActionPerformed(evt);
            }
        });
        jPanel1.add(quantity_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 120, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Cost Price");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 70, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Supllier Name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 90, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Unit of Measure");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 420, 100, 30));

        productStat_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        productStat_cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productStat_cmbActionPerformed(evt);
            }
        });
        jPanel1.add(productStat_cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 150, 30));

        productID_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productID_txtActionPerformed(evt);
            }
        });
        jPanel1.add(productID_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 200, 30));

        supplier_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_txtActionPerformed(evt);
            }
        });
        jPanel1.add(supplier_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 200, -1));

        category_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        category_cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_cmbActionPerformed(evt);
            }
        });
        jPanel1.add(category_cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 200, 30));

        unitMeasure_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        unitMeasure_cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitMeasure_cmbActionPerformed(evt);
            }
        });
        jPanel1.add(unitMeasure_cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 150, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Product ID");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("PRODUCT INFORMATION");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, 20));

        panel1.setBackground(new java.awt.Color(102, 102, 102));
        panel1.setMaximumSize(new java.awt.Dimension(1, 1));
        panel1.setMinimumSize(new java.awt.Dimension(1, 1));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 650, 3));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("PRODUCT INFORMATION");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 230, 20));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg.jpg"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 290, 290));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 260, 290));

        product_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Category", "Description", "Cost Price", "Selling Price", "Quantity", "Reorder", "Supplier", "Unit Measure", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        product_tbl.setMaximumSize(new java.awt.Dimension(165, 80));
        product_tbl.setPreferredSize(new java.awt.Dimension(165, 80));
        product_tbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(product_tbl);
        if (product_tbl.getColumnModel().getColumnCount() > 0) {
            product_tbl.getColumnModel().getColumn(0).setResizable(false);
            product_tbl.getColumnModel().getColumn(1).setResizable(false);
            product_tbl.getColumnModel().getColumn(2).setResizable(false);
            product_tbl.getColumnModel().getColumn(3).setResizable(false);
            product_tbl.getColumnModel().getColumn(4).setResizable(false);
            product_tbl.getColumnModel().getColumn(5).setResizable(false);
            product_tbl.getColumnModel().getColumn(6).setResizable(false);
            product_tbl.getColumnModel().getColumn(7).setResizable(false);
            product_tbl.getColumnModel().getColumn(8).setResizable(false);
            product_tbl.getColumnModel().getColumn(9).setResizable(false);
            product_tbl.getColumnModel().getColumn(10).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 650, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) product_tbl.getModel();

    // Get values from fields
    String productID = productID_txt.getText();
    String productName = productName_txt.getText();
    String category = category_cmb.getSelectedItem().toString();
    String description = description_txt.getText();
    String costPrice = costPrice_txt.getText();
    String sellingPrice = sellingPrice_txt.getText();
    String quantity = quantity_txt.getText();
    String reorder = reorder_txt.getText();
    String supplier = supplier_txt.getText();
    String unitMeasure = unitMeasure_cmb.getSelectedItem().toString();
    String productStatus = productStat_cmb.getSelectedItem().toString();

    // Simple validation (optional)
    if (productID.isEmpty() || productName.isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Product ID and Product Name are required!",
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // Add all data to table
    model.addRow(new Object[] {
        productID,
        productName,
        category,
        description,
        costPrice,
        sellingPrice,
        quantity,
        reorder,
        supplier,
        unitMeasure,
        productStatus
    });

    // Clear all input fields after adding
    productID_txt.setText("");
    productName_txt.setText("");
    description_txt.setText("");
    costPrice_txt.setText("");
    sellingPrice_txt.setText("");
    quantity_txt.setText("");
    reorder_txt.setText("");
    supplier_txt.setText("");

    category_cmb.setSelectedIndex(0);
    unitMeasure_cmb.setSelectedIndex(0);
    productStat_cmb.setSelectedIndex(0);

    // Focus back to Product ID for next entry
    productID_txt.requestFocus();
    }//GEN-LAST:event_add_btnActionPerformed

    private void productName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productName_txtActionPerformed

    private void reorder_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reorder_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reorder_txtActionPerformed

    private void costPrice_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costPrice_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costPrice_txtActionPerformed

    private void sellingPrice_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellingPrice_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellingPrice_txtActionPerformed

    private void quantity_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantity_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantity_txtActionPerformed

    private void productStat_cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productStat_cmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productStat_cmbActionPerformed

    private void productID_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productID_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productID_txtActionPerformed

    private void supplier_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplier_txtActionPerformed

    private void category_cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_cmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_category_cmbActionPerformed

    private void unitMeasure_cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitMeasure_cmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitMeasure_cmbActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
         int choice = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to go back to Dashboard?",
        "Confirm Exit",
        JOptionPane.YES_NO_OPTION
    );

    if (choice == JOptionPane.YES_OPTION) {
        this.dispose();
    }
    }//GEN-LAST:event_exit_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        int selectedRow = product_tbl.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row to update!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Get table model
    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) product_tbl.getModel();

    // Update the selected row with values from fields
    model.setValueAt(productID_txt.getText(), selectedRow, 0);
    model.setValueAt(productName_txt.getText(), selectedRow, 1);
    model.setValueAt(category_cmb.getSelectedItem().toString(), selectedRow, 2);
    model.setValueAt(description_txt.getText(), selectedRow, 3);
    model.setValueAt(costPrice_txt.getText(), selectedRow, 4);
    model.setValueAt(sellingPrice_txt.getText(), selectedRow, 5);
    model.setValueAt(quantity_txt.getText(), selectedRow, 6);
    model.setValueAt(reorder_txt.getText(), selectedRow, 7);
    model.setValueAt(supplier_txt.getText(), selectedRow, 8);
    model.setValueAt(unitMeasure_cmb.getSelectedItem().toString(), selectedRow, 9);
    model.setValueAt(productStat_cmb.getSelectedItem().toString(), selectedRow, 10);

    JOptionPane.showMessageDialog(this, "Product updated successfully!");
    
    // ✅ CLEAR FIELDS AFTER UPDATE
    productID_txt.setText("");
    productName_txt.setText("");
    description_txt.setText("");
    costPrice_txt.setText("");
    sellingPrice_txt.setText("");
    quantity_txt.setText("");
    reorder_txt.setText("");
    supplier_txt.setText("");

    category_cmb.setSelectedIndex(0);
    unitMeasure_cmb.setSelectedIndex(0);
    productStat_cmb.setSelectedIndex(0);
    }//GEN-LAST:event_update_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
            int choice = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to clear all fields?",
        "Confirm Clear",
        JOptionPane.YES_NO_OPTION
    );

    if (choice == JOptionPane.YES_OPTION) {
        productID_txt.setText("");
        productName_txt.setText("");
        description_txt.setText("");
        costPrice_txt.setText("");
        sellingPrice_txt.setText("");
        quantity_txt.setText("");
        reorder_txt.setText("");
        supplier_txt.setText("");


       category_cmb.setSelectedIndex(0);
       unitMeasure_cmb.setSelectedIndex(0);
       productStat_cmb.setSelectedIndex(0);

     // 🔥 CLEAR TABLE DATA
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) product_tbl.getModel();
    model.setRowCount(0); // removes all rows

    productID_txt.requestFocus();
    }
    }//GEN-LAST:event_clear_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button add_btn;
    private javax.swing.JComboBox<String> category_cmb;
    private java.awt.Button clear_btn;
    private javax.swing.JTextField costPrice_txt;
    private javax.swing.JTextArea description_txt;
    private java.awt.Button exit_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel1;
    private javax.swing.JTextField productID_txt;
    private javax.swing.JTextField productName_txt;
    private javax.swing.JComboBox<String> productStat_cmb;
    private javax.swing.JTable product_tbl;
    private javax.swing.JTextField quantity_txt;
    private javax.swing.JTextField reorder_txt;
    private javax.swing.JTextField sellingPrice_txt;
    private javax.swing.JTextField supplier_txt;
    private javax.swing.JComboBox<String> unitMeasure_cmb;
    private java.awt.Button update_btn;
    // End of variables declaration//GEN-END:variables
}
